apiVersion: v1
kind: Service
metadata:
  name: table-db
spec:
  clusterIP: None
  selector:
    app: table-db
  ports:
    - port: 5432
      name: table-db-port

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: table-db
spec:
  serviceName: table-db
  replicas: 1
  selector:
    matchLabels:
      app: table-db
  template:
    metadata:
      labels:
        app: table-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          args: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
          ports:
            - containerPort: 5432
              name: table-db-port
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: online_excel
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TABLE_DB_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
          readinessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: postgres-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi