services:
  # API Gateway
  api_gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    container_name: online_excel_gateway
#    env_file:
#      - .env
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - backend
    networks:
      - appnet
    volumes:
      - ./api_gateway:/app/api_gateway

  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    container_name: online_excel_auth_service
    ports:
      - "8001:8001"
    environment:
      DB_HOST: auth_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      DB_DRIVER: postgresql+asyncpg
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      JWT_SECRET_KEY: "secret"
      JWT_ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 30
    restart: on-failure
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - appnet

  auth_db:
    container_name: online_excel_auth_db
    image: postgres:16-alpine
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "8010:5432"
    networks:
      - appnet
    volumes:
      - auth_pgdata:/var/lib/postgresql/data


  db:
    container_name: online_excel_db
    image: postgres:16-alpine
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: online_excel
      POSTGRES_USER: postgres
      POSTGRES_DB: online_excel
    ports:
      - "7777:5432"
    networks:
      - appnet
    volumes:
      - pgdata:/var/lib/postresql/data

  backend:
    build:
      context: .
      dockerfile: table_service/Dockerfile
    container_name: table_service
    environment:
      EXCEL_APP__DB_HOST: db
      EXCEL_APP__DB_PORT: 5432
      EXCEL_APP__DB_USER: postgres
      EXCEL_APP__DB_PASSWORD: online_excel
      EXCEL_APP__DB_NAME: online_excel
      EXCEL_APP__DB_DRIVER: postgresql+asyncpg
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: online_excel_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pgdata:
  auth_pgdata: