apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: online-excel

resources:
  - k8s/base/namespace.yaml
  - k8s/base/infra/table-db.yaml
  - k8s/base/jobs/table-migrate.yaml
  - k8s/base/apps/table-service.yaml
  - k8s/base/infra/auth-db.yaml
  - k8s/base/jobs/auth-migrate.yaml
  - k8s/base/apps/auth-service.yaml

configMapGenerator:
  - name: postgres-config
    files:
      - infra/postgres/postgresql.conf