apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: auth-public
  namespace: online-excel
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/auth`)
      kind: Rule
      middlewares:
        - name: ratelimit@file
        - name: body-limit@file
        - name: cors@file
      services:
        - name: auth-service
          port: 8001

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: users-protected
  namespace: online-excel
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/users`)
      kind: Rule
      middlewares:
        - name: ratelimit@file
        - name: body-limit@file
        - name: cors@file
        - name: strip-user-headers@file
        - name: jwt-auth@file
      services:
        - name: auth-service
          port: 8001