apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: table-ws
  namespace: online-excel
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/ws/tables`)
      kind: Rule
      middlewares:
        - name: rate-limit
        - name: cors
        - name: strip-user-headers
      services:
        - name: table-service
          port: 8000