apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: table-protected
  namespace: online-excel
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/tables`) || PathPrefix(`/data`) || PathPrefix(`/search`)
      kind: Rule
      middlewares:
        - name: ratelimit@file
        - name: body-limit@file
        - name: cors@file
        - name: strip-user-headers@file
        - name: jwt-auth@file
      services:
        - name: table-service
          port: 8000