"""initial chat schema

Revision ID: 94fa49f3dff4
Revises:
Create Date: 2026-07-12 22:25:27.344388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94fa49f3dff4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_users_email"), "chat_users", ["email"], unique=True)
    op.create_index(op.f("ix_chat_users_id"), "chat_users", ["id"], unique=False)
    op.create_table(
        "chats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user1_email", sa.String(length=255), nullable=False),
        sa.Column("user2_email", sa.String(length=255), nullable=False),
        sa.Column("last_message_content", sa.Text(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unread_count_user1", sa.Integer(), nullable=False),
        sa.Column("unread_count_user2", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user1_email"],
            ["chat_users.email"],
        ),
        sa.ForeignKeyConstraint(
            ["user2_email"],
            ["chat_users.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user1_email", "user2_email", name="uq_chat_users_pair"),
    )
    op.create_index(op.f("ix_chats_id"), "chats", ["id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("sender_email", sa.String(length=255), nullable=False),
        sa.Column("receiver_email", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["receiver_email"],
            ["chat_users.email"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_email"],
            ["chat_users.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_message_chat_created", "messages", ["chat_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_message_chat_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_chats_id"), table_name="chats")
    op.drop_table("chats")
    op.drop_index(op.f("ix_chat_users_id"), table_name="chat_users")
    op.drop_index(op.f("ix_chat_users_email"), table_name="chat_users")
    op.drop_table("chat_users")
    # ### end Alembic commands ###
