"""add_cascade_delete

Revision ID: af8617b1de07
Revises: 843df84fccb0
Create Date: 2025-12-29 13:38:16.400295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8617b1de07'
down_revision: Union[str, Sequence[str], None] = '843df84fccb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('table_permissions_table_id_fkey'), 'table_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'table_permissions', 'data_tables', ['table_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('table_rows_table_id_fkey'), 'table_rows', type_='foreignkey')
    op.create_foreign_key(None, 'table_rows', 'data_tables', ['table_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_rows', type_='foreignkey')
    op.create_foreign_key(op.f('table_rows_table_id_fkey'), 'table_rows', 'data_tables', ['table_id'], ['id'])
    op.drop_constraint(None, 'table_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('table_permissions_table_id_fkey'), 'table_permissions', 'data_tables', ['table_id'], ['id'])
    # ### end Alembic commands ###
