global:
  scrape_interval: 10s

scrape_configs:

  - job_name: "docker-sd"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    relabel_configs:
      # Оставить только контейнеры с лейблом prometheus.scrape=true
      - source_labels: [ __meta_docker_container_label_prometheus_scrape ]
        regex: "true"
        action: keep

      # Взять путь /metrics из лейбла (если указан)
      - source_labels: [ __meta_docker_container_label_prometheus_path ]
        regex: "(.+)"
        target_label: __metrics_path__

      # Взять порт из лейбла контейнера
      - source_labels: [ __address__, __meta_docker_container_label_prometheus_port ]
        regex: "([^:]+)(?::\\d+)?;(\\d+)"
        replacement: "$1:$2"
        target_label: __address__

      # Имя контейнера → лейбл job
      - source_labels: [ __meta_docker_container_name ]
        regex: "/?(.*)"
        target_label: job

      - source_labels: [ __meta_docker_container_label_prometheus_port ]
        target_label: port
