apiVersion: v1
kind: ConfigMap
metadata:
  name: table-service-config
data:
  EXCEL_APP__DB_HOST: table-db
  EXCEL_APP__DB_PORT: "5432"
  EXCEL_APP__DB_USER: postgres
  EXCEL_APP__DB_NAME: online_excel
  EXCEL_APP__DB_DRIVER: postgresql+asyncpg
  EXCEL_APP__CACHE_HOST: redis
  EXCEL_APP__CACHE_PORT: "6379"
  EXCEL_APP__CACHE_DB: "0"
  EXCEL_APP__ES_HOST: elasticsearch
  EXCEL_APP__ES_PORT: "9200"
  EXCEL_APP__RABBITMQ_HOST: rabbitmq
  EXCEL_APP__RABBITMQ_PORT: "5672"
  EXCEL_APP__RABBITMQ_USER: guest