apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
  namespace: online-excel
type: Opaque
stringData:
  jwt_private.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDL31V1zrOldfSS
    aw2LQeaV4sp7ONDv4hpTnOI2WKNrzsSlBFNDgJ3aXAt8u0sejkKBpYU0IN1VGsET
    6HtfUeiRZtP7qI0eN2kPcAH00AcxMAE9FSs3mDpWEtB9qDDm4VSiEpJenH0bYA5O
    oSWgGOXBf9wavrwYyBUKhnNvi0wp/DdPW1P47jy1Rl0pla69b0XfiSL9s/60zbQs
    YuUk8p1jUgmw2nORRRhNv4fRFthbGifDpOTEa4a8jW4fPMh4C2V58ctDNjnEwiNg
    FwWBf4sOo96DmqVxvKDlxgJJw2zWKxzmjWn9DCZGdEt8Yhf1PIhNBknIQMYJkhSr
    S7lMSmvFAgMBAAECggEAGJEWuf24uZ9DY7JpPSbpi5W62wrfaIypKfqtaqmXNbpC
    iXUCOI/i1amCS9tA49N2Mau5p6yvJx50djrtRPD4kq7erARlTucT7qOLZM39k+CK
    QatPnCEopG8bdwzhqays92PABg0a6UXTq4dxIn/ljcHjyshBn8XafTxy5BXXzXYr
    PmkV4Y8cOt/koZqIbNXpGQTWxiwTFM3wfUMc9RodY1FFkbg+abmZjj9HpF3ZZnB8
    nasVqb7yWWCvLWM2qJYK98tOhhHCFSdyNgyAGgGiWoSHzW5m2GYZikcTh72hj1zA
    OBB/elnrPnRfUx2dPyPnQOt+rrcntkEYLniwoPvdkQKBgQDn+/HHfLJKqRedFff4
    kSLHuvJkw0zFp4sUgQDPd+wOEWwQELXKd2/9wVlGoIKXYuDWl45Ugqw21QxqHkla
    VYM4yLPMN16FqtJGQz7cc9u0Ujaa2rLf0gVAjjDOr4PkUT6RGPK7X/yaD0VnsO2t
    f8wkVsbN99HoHQ76fY/ddsowkQKBgQDg+l7AtiFKNmJ8kdcJ+06LlPAW2JFGXNVn
    TIu5depdtXnnFWxq/gCphIDW8tOFmAH7B2Lmv8dMt40OeMw0dvAEwrzz5BU5jd1w
    fFP2LPRjzpuobV/M/SZtuddSKS7OBzg0BpGlCAFvd2NYvLL98eN89/+ewI/7h/JZ
    YVpY27Nh9QKBgQDEoCtiJjMITSISpxgyuvF70Ny6wz5DGassidsh/kc59VJem4s6
    PNnTfxooXsvRfKGNwY+F2ewV3aZUG6+YvXonmxWqNhQLv6nSnBSfziOeR0C5KD0M
    sHp7KQn9ZY6o6qPZYAf9AXKdMexl4vTRZcyl0FdZJH/p+RdFAT/7OkBNwQKBgQCX
    h2q8Z6+CWaD6AAyTN4WOs/EFojYu6yX9HmxZrNb+6NVDVIWihpQRmSJiJEldiKWE
    21O80Vy+Cj7iiXAYwiclPbigmHXHPwrv0X2HqH2un6Dtz0UgPz1b2DjzqLNSp0Au
    omIEgqDc38+1G9t++SXcrPiph08y/jy4AL8mbEuk5QKBgBxUyV9dORW3S8RXmCrM
    RUNsNZYL3FVB0s6Gu3hXykZNGb4xV1F6L49WfY1Mg2VdQghQGwVm59mpWyNduUe1
    QLWM3Te4SHUouDIMAQD/w/bsf+qD64fDXesoB13F+pKVkl8xxZ6fEI9xpIJ4fDhp
    kJUe/d4K2AStieIvfBmO890o
    -----END PRIVATE KEY-----

  jwt_public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy99Vdc6zpXX0kmsNi0Hm
    leLKezjQ7+IaU5ziNlija87EpQRTQ4Cd2lwLfLtLHo5CgaWFNCDdVRrBE+h7X1Ho
    kWbT+6iNHjdpD3AB9NAHMTABPRUrN5g6VhLQfagw5uFUohKSXpx9G2AOTqEloBjl
    wX/cGr68GMgVCoZzb4tMKfw3T1tT+O48tUZdKZWuvW9F34ki/bP+tM20LGLlJPKd
    Y1IJsNpzkUUYTb+H0RbYWxonw6TkxGuGvI1uHzzIeAtlefHLQzY5xMIjYBcFgX+L
    DqPeg5qlcbyg5cYCScNs1isc5o1p/QwmRnRLfGIX9TyITQZJyEDGCZIUq0u5TEpr
    xQIDAQAB
    -----END PUBLIC KEY-----
