apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  TABLE_DB_PASSWORD: online_excel
  AUTH_DB_PASSWORD: postgres
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  JWT_SECRET_KEY: local_dev_secret
  JWT_ALGORITHM: RS256
  JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private.pem
  JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public.pem
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin