"""add_constraint_unique_table_permissions

Revision ID: 2c0451adbe8c
Revises: a1e02152a4da
Create Date: 2026-10-07 12:03:12.735312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0451adbe8c'
down_revision: Union[str, Sequence[str], None] = 'a1e02152a4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_table_permission_table_user', 'table_permissions', ['user_id', 'table_id'])
    op.create_index('ix_table_pins_table_id', 'table_pins', ['table_id'], unique=False)
    op.create_foreign_key(None, 'table_pins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_pins', type_='foreignkey')
    op.drop_index('ix_table_pins_table_id', table_name='table_pins')
    op.drop_constraint('uq_table_permission_table_user', 'table_permissions', type_='unique')
    # ### end Alembic commands ###
