"""add_soft_delete_to_tables

Revision ID: ba5eae50baf0
Revises: c2c4dc200571
Create Date: 2026-06-12 09:34:30.574313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba5eae50baf0"
down_revision: str | Sequence[str] | None = "c2c4dc200571"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_tables",
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "data_tables",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_tables", "deleted_at")
    op.drop_column("data_tables", "is_deleted")
    # ### end Alembic commands ###
