"""init

Revision ID: c1c830751321
Revises: 
Create Date: 2026-06-05 13:30:08.374249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1c830751321'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_permissions_id'), table_name='table_permissions')
    op.drop_table('table_permissions')
    op.drop_index(op.f('ix_data_tables_id'), table_name='data_tables')
    op.drop_index(op.f('ix_data_tables_name'), table_name='data_tables')
    op.drop_table('data_tables')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_table_rows_id'), table_name='table_rows')
    op.drop_index(op.f('ix_table_rows_table_id_created'), table_name='table_rows')
    op.drop_index(op.f('ix_table_rows_table_id_updated'), table_name='table_rows')
    op.drop_table('table_rows')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_rows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('row_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['data_tables.id'], name=op.f('table_rows_table_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('table_rows_pkey'))
    )
    op.create_index(op.f('ix_table_rows_table_id_updated'), 'table_rows', ['table_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_table_rows_table_id_created'), 'table_rows', ['table_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_table_rows_id'), 'table_rows', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('data_tables',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('data_tables_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('columns_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_tables_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_data_tables_name'), 'data_tables', ['name'], unique=False)
    op.create_index(op.f('ix_data_tables_id'), 'data_tables', ['id'], unique=False)
    op.create_table('table_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('can_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('can_write', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('can_manage', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['data_tables.id'], name=op.f('table_permissions_table_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('table_permissions_pkey'))
    )
    op.create_index(op.f('ix_table_permissions_id'), 'table_permissions', ['id'], unique=False)
    # ### end Alembic commands ###
