"""add_formulas_column

Revision ID: c2c4dc200571
Revises: 55f18a347d39
Create Date: 2026-06-08 10:46:21.730201

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2c4dc200571"
down_revision: str | Sequence[str] | None = "55f18a347d39"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("table_rows", sa.Column("formulas", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("table_rows", "formulas")
    # ### end Alembic commands ###
