name: CI - API Gateway Service

on:
  pull_request:
    paths:
      - 'api_gateway/**'
      - 'docker-compose.yml'
      - '.github/workflows/ci-gateway-service.yml'
  push:
    branches: [ main, develop ]
    paths:
      - 'api_gateway/**'

env:
  PYTHON_VERSION: '3.13'
  SERVICE_NAME: api_gateway


jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    container: python:${{ env.PYTHON_VERSION }}-slim

    defaults:
      run:
        working-directory: ./${{ env.SERVICE_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff linter
        run: ruff check . --output-format=github

      - name: Run Ruff formatter check
        run: ruff format --check .

  unit-tests:
    runs-on: ubuntu-latest
    container: python:${{ env.PYTHON_VERSION }}
    needs: [ lint-and-type-check ]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov httpx
          pip install -r api_gateway/requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/unit/api_gateway \
          -v \
          --cov=api_gateway \
          --cov-report=xml \
          --cov-report=term \
          -m "not integration"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
